plugins:
  # Beware: the part before "_enable" has to be the common settings name part
  cfbtn_enabled:
    default: true
    client: true
  cfbtn_openhab_items:
    default: false
    client: true
  cfbtn_openhab_rules:
    default: false
    client: true
  cfbtn_openhab_sitemap:
    default: false
    client: true
  cfbtn_javascript:
    default: true
    client: true
  cfbtn_custom1:
    default: ""
    client: true
