plugins:
  cfbtn_plugin_enabled:
    default: true
    client: true
  cfbtn_openhab_items:
    default: false
    client: true
  cfbtn_openhab_rules:
    default: false
    client: true
  cfbtn_openhab_sitemap:
    default: false
    client: true
